services:
  gate-video-stream:
    build:
      context: . 
      dockerfile: ./Dockerfile.prod
    command:
      node /app/app/gate-video-stream.js
    environment:
      - ENV_ID=prod
      - PORT=8900
    ports:
      - 8900:8900
      - 8950:8950
    restart: always
    network_mode: host
