services:
  gate-video-stream:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    command:
      pnpm run dev
    environment:
      - ENV_ID=dev
      - PORT=8900
    tty: true
    ports:
      - 8900:8900
      - 8950:8950
    volumes:
      - .:/app/
    restart: always
