CREATE TABLE IF NOT EXISTS `entrance_heatmaps` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int unsigned NOT NULL,
  `box_id` int unsigned NOT NULL,
  `heatmap_date` date NOT NULL,
  `image_url` varchar(1024) DEFAULT NULL,
  `s3_key` varchar(512) DEFAULT NULL,
  `width` int unsigned DEFAULT NULL,
  `height` int unsigned DEFAULT NULL,
  `grid_width` int unsigned NOT NULL DEFAULT 96,
  `grid_height` int unsigned NOT NULL DEFAULT 72,
  `heat_grid` json DEFAULT NULL,
  `trajectory_count` int unsigned NOT NULL DEFAULT 0,
  `point_count` int unsigned NOT NULL DEFAULT 0,
  `last_sample_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `entrance_heatmaps_user_box_date` (`user_id`, `box_id`, `heatmap_date`),
  KEY `entrance_heatmaps_user_box_updated` (`user_id`, `box_id`, `updated_at`),
  KEY `entrance_heatmaps_user_box_date_idx` (`user_id`, `box_id`, `heatmap_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
